#!/bin/sh

# tokenizing
./utf8-tokenize.perl -e -a english-abbreviations $* |
# remove empty lines
grep -v '^$' |

# tagging
./tree-tagger -token -lemma -sgml english-utf8.par | 
    perl -pe 's/\tV[BDHV]/\tVB/;s/\tIN\/that/\tIN/;'
